# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3e3d501eb6f56a8eabdccfc150cf15f29df071ed86a9a47217b73e6337c8a7c01bd4ddca0e58244952f623ed121d81082d275c25e174e08af9bd0ec8619d757

test:
  secret_key_base: 0cc5546a8325de023c86d4cfbeb7d97492d1c917e07a1161907fdde6e0b92345feb707882cbe9b4ee03aad80a4147983a1fef2014aee28a12bae9886a876c3e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
